# -*- coding: utf-8 -*-
"""YourName_AI/ML_Week2.py .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XhblnVKF-QG6da-CHZ9Wzi9fhTWUbu3Y
"""

# Task 1: Python Basics & Operators
import random
import numpy as np
from datetime import datetime

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print(f"Addition: {num1 + num2}")
print(f"Subtraction: {num1 - num2}")
print(f"Multiplication: {num1 * num2}")
print(f"Division: {num1 / num2}")
print(f"Modulus: {num1 % num2}")
print(f"Power: {num1 ** num2}")

print(f"{num1} > {num2}: {num1 > num2}")
print(f"{num1} < {num2}: {num1 < num2}")
print(f"{num1} == {num2}: {num1 == num2}")
print(f"{num1} != {num2}: {num1 != num2}")

# Task 2: Lists and Arrays
import random
import numpy as np
from datetime import datetime

numbers = [random.randint(1, 100) for _ in range(10)]
numbers.append(50)
numbers.pop(0)

print("List:", numbers)
print("Max:", max(numbers))
print("Min:", min(numbers))

array = np.array(numbers)
print("Mean:", np.mean(array))
print("Median:", np.median(array))
print("Std Dev:", np.std(array))

# Task 3: Dictionary & Sets

import random
import numpy as np
from datetime import datetime

student = {"name": "Rahul", "course": "AI/ML", "marks": 82}

if student["marks"] >= 80:
    student["grade"] = "A"
elif student["marks"] >= 60:
    student["grade"] = "B"
else:
    student["grade"] = "C"

for k, v in student.items():
    print(k, ":", v)

ai_tools_1 = {"ChatGPT", "TensorFlow", "PyTorch"}
ai_tools_2 = {"PyTorch", "Keras", "Scikit-learn"}
print("Common AI Tools:", ai_tools_1 & ai_tools_2)

#Task 4: File Handling

import random
import numpy as np
from datetime import datetime

with open("ai_students.txt", "w") as f:
    f.write("Amit, 78, B\nSneha, 85, A\nRahul, 72, B\nPriya, 90, A\nKaran, 65, B\n")

with open("ai_students.txt", "r") as f:
    for line in f:
        name, marks, grade = line.strip().split(", ")
        if int(marks) > 75:
            print("Above 75:", name)

# Task 5: Prompt Logger
import random
import numpy as np
from datetime import datetime

prompt = input("Enter AI prompt: ")
timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

with open("prompt_history.txt", "a") as f:
    f.write(f"[{timestamp}] {prompt}\n")

print("Prompt saved!")